"""empty message

Revision ID: 25540d719a12
Revises: 35dbe228c5d6
Create Date: 2014-04-19 01:39:14.752660

"""

# revision identifiers, used by Alembic.
revision = '25540d719a12'
down_revision = '35dbe228c5d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'url_big',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
    op.alter_column('images', 'url_medium',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
    op.alter_column('images', 'url_small',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'url_small',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
    op.alter_column('images', 'url_medium',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
    op.alter_column('images', 'url_big',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
    ### end Alembic commands ###
