"""empty message

Revision ID: 35dbe228c5d6
Revises: 484a6436d75f
Create Date: 2014-04-19 01:21:28.596324

"""

# revision identifiers, used by Alembic.
revision = '35dbe228c5d6'
down_revision = '484a6436d75f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url_big', sa.String(length=4096), nullable=False))
    op.add_column('images', sa.Column('url_medium', sa.String(length=4096), nullable=False))
    op.add_column('images', sa.Column('url_small', sa.String(length=4096), nullable=False))
    op.drop_column('images', 'url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.VARCHAR(length=4096), nullable=False))
    op.drop_column('images', 'url_small')
    op.drop_column('images', 'url_medium')
    op.drop_column('images', 'url_big')
    ### end Alembic commands ###
