"""empty message

Revision ID: 4776348aabe9
Revises: 25540d719a12
Create Date: 2014-04-19 14:50:16.073269

"""

# revision identifiers, used by Alembic.
revision = '4776348aabe9'
down_revision = '25540d719a12'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('lng', sa.Float(), nullable=True))
    op.drop_column('entities', 'long')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('long', postgresql.DOUBLE_PRECISION(precision=53), nullable=True))
    op.drop_column('entities', 'lng')
    ### end Alembic commands ###
