"""empty message

Revision ID: 484a6436d75f
Revises: None
Create Date: 2014-04-18 22:48:00.366595

"""

# revision identifiers, used by Alembic.
revision = '484a6436d75f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('alien_site', sa.Enum('twitter', 'vk', 'instagram', name='alien_site_types'), nullable=True),
    sa.Column('alien_id', sa.BigInteger(), nullable=True),
    sa.Column('alien_name', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=4096), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('entities')
    ### end Alembic commands ###
