"""empty message

Revision ID: eef06fdf6a4
Revises: None
Create Date: 2014-05-04 01:21:53.590136

"""

# revision identifiers, used by Alembic.
revision = 'eef06fdf6a4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('alien_site', sa.Enum('twitter', 'vk', 'instagram', name='alien_site_types'), nullable=True),
    sa.Column('alien_id', sa.BigInteger(), nullable=True),
    sa.Column('alien_name', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=4096), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('img_small', sa.String(length=4096), nullable=True),
    sa.Column('img_medium', sa.String(length=4096), nullable=True),
    sa.Column('img_big', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('entities')
    ### end Alembic commands ###
